# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AccessRequestCreateNewRequestRequest(BaseModel):
    # The ID of a dataset in the catalog
    data_set_id: str = Field(alias='dataSetId')

    # ID for the entity which is requesting access.
    requesting_entity_id: str = Field(alias='requestingEntityId')

    # Free text message provided by the user when requesting access.
    request_message: str = Field(alias='requestMessage')

    # Name of the user who requested access.
    requester_name: typing.Optional[str] = Field(None, alias='requesterName')

    # Contact email address for the user who requested access.
    requester_email: typing.Optional[str] = Field(None, alias='requesterEmail')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
