# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


AccrualPeriodicity = Literal["Hourly", "Daily", "Three times a week", "Semiweekly", "Weekly", "Three times a month", "Biweekly", "Semimonthly", "Monthly", "Bimonthly", "Quarterly", "Three times a year", "Semiannual", "Annual", "Biennial", "Triennial", "Continuous", "Irregular", "continual", "daily", "weekly", "fortnightly", "monthly", "quarterly", "biannually", "annually", "asNeeded", "irregular", "notPlanned", "unknown"]
