# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AuthenticationGetJwtRequest(BaseModel):
    # Agrimetrics Catalog username
    username: typing.Optional[str] = Field(None, alias='username')

    # Agrimetrics Catalog password
    password: typing.Optional[str] = Field(None, alias='password')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
