# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from agrimetrics_python_sdk.pydantic.entry_type import EntryType

class BasicDataSetInfo(BaseModel):
    # Title for the data set.
    title: str = Field(alias='title')

    # The ID of a dataset in the catalog
    id: str = Field(alias='id')

    entry_type: EntryType = Field(alias='entryType')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
