# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from agrimetrics_python_sdk.pydantic.entitlements import Entitlements
from agrimetrics_python_sdk.pydantic.identity_input import IdentityInput

class BatchIdentityInputEntitlementsItem(BaseModel):
    identity: IdentityInput = Field(alias='identity')

    entitlements: Entitlements = Field(alias='entitlements')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
