# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class CostSummary(BaseModel):
    total_cost: typing.Union[int, float] = Field(alias='totalCost')

    number_of_chargeable_items: int = Field(alias='numberOfChargeableItems')

    total_number_of_items: typing.Optional[int] = Field(None, alias='totalNumberOfItems')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
