# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from agrimetrics_python_sdk.pydantic.exchange import Exchange

class CreateFromTemplatePayload(BaseModel):
    # The ID of a template in the catalog
    template_id: str = Field(alias='templateId')

    # Title for the data set.
    title: typing.Optional[str] = Field(None, alias='title')

    # Description of the data set.
    description: typing.Optional[str] = Field(None, alias='description')

    exchange: typing.Optional[Exchange] = Field(None, alias='exchange')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
