# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from agrimetrics_python_sdk.pydantic.batch_identity_input_entitlements import BatchIdentityInputEntitlements
from agrimetrics_python_sdk.pydantic.data_set_patch import DataSetPatch
from agrimetrics_python_sdk.pydantic.entitlements import Entitlements
from agrimetrics_python_sdk.pydantic.exchange import Exchange

class DataSetTemplateMetadata(BaseModel):
    name: str = Field(alias='name')

    description: typing.Optional[str] = Field(None, alias='description')

    data_set: typing.Optional[DataSetPatch] = Field(None, alias='dataSet')

    entitlements: typing.Optional[BatchIdentityInputEntitlements] = Field(None, alias='entitlements')

    creator_entitlements: typing.Optional[Entitlements] = Field(None, alias='creatorEntitlements')

    exchange: typing.Optional[Exchange] = Field(None, alias='exchange')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
