# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class DataRequestResponseItem(BaseModel):
    # The ID of the data request
    request_id: str = Field(alias='requestId')

    # The ID of the dataset that the data request relates to
    dataset_id: str = Field(alias='datasetId')

    # The name of the dataset that the data request relates to
    dataset_name: str = Field(alias='datasetName')

    # The status of the data request
    status: Literal["pending", "approved", "denied", "cancelled"] = Field(alias='status')

    # The date the data request was made
    requested_date: str = Field(alias='requestedDate')

    # The requesters email address
    requester_email: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='requesterEmail')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
