# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from agrimetrics_python_sdk.pydantic.output_formats import OutputFormats
from agrimetrics_python_sdk.pydantic.point_search_base import PointSearchBase

PointSearch = typing.Union[PointSearchBase,typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
