# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class PublicContact(BaseModel):
    # Organisation name for this contact
    organisation_name: str = Field(alias='organisationName')

    # The role of this contact as it relates to the data set
    role: Literal["pointOfContact"] = Field(alias='role')

    # Support url for this contact
    url: typing.Optional[str] = Field(None, alias='url')

    # Title of the support website
    url_label: typing.Optional[str] = Field(None, alias='urlLabel')

    # Email address for this contact
    email_address: typing.Optional[str] = Field(None, alias='emailAddress')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
