# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class Resource(BaseModel):
    # URL to obtain more information on this data set.
    url: str = Field(alias='url')

    # Description of what the URL represents.
    description: typing.Optional[str] = Field(None, alias='description')

    # ID for this resource item.
    id: typing.Optional[str] = Field(None, alias='id')

    # Name for what the URL represents.
    name: typing.Optional[str] = Field(None, alias='name')

    # Indicates whether the resource metadata is sensitive data.
    private: typing.Optional[bool] = Field(None, alias='private')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
