# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class TaxonomyKeywords(BaseModel):
    value_uri: str = Field(alias='valueUri')

    value_label: str = Field(alias='valueLabel')

    source_uri: str = Field(alias='sourceUri')

    source_label: str = Field(alias='sourceLabel')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
