# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from agrimetrics_python_sdk import schemas  # noqa: F401


class BoundingBoxCoordinates(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "minlon",
            "maxlat",
            "minlat",
            "maxlon",
        }
        
        class properties:
        
            @staticmethod
            def minlat() -> typing.Type['EPSG4326Latitude']:
                return EPSG4326Latitude
        
            @staticmethod
            def minlon() -> typing.Type['EPSG4326Longitude']:
                return EPSG4326Longitude
        
            @staticmethod
            def maxlat() -> typing.Type['EPSG4326Latitude']:
                return EPSG4326Latitude
        
            @staticmethod
            def maxlon() -> typing.Type['EPSG4326Longitude']:
                return EPSG4326Longitude
            __annotations__ = {
                "minlat": minlat,
                "minlon": minlon,
                "maxlat": maxlat,
                "maxlon": maxlon,
            }
    
    minlon: 'EPSG4326Longitude'
    maxlat: 'EPSG4326Latitude'
    minlat: 'EPSG4326Latitude'
    maxlon: 'EPSG4326Longitude'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["minlat"]) -> 'EPSG4326Latitude': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["minlon"]) -> 'EPSG4326Longitude': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["maxlat"]) -> 'EPSG4326Latitude': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["maxlon"]) -> 'EPSG4326Longitude': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["minlat", "minlon", "maxlat", "maxlon", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["minlat"]) -> 'EPSG4326Latitude': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["minlon"]) -> 'EPSG4326Longitude': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["maxlat"]) -> 'EPSG4326Latitude': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["maxlon"]) -> 'EPSG4326Longitude': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["minlat", "minlon", "maxlat", "maxlon", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        minlon: 'EPSG4326Longitude',
        maxlat: 'EPSG4326Latitude',
        minlat: 'EPSG4326Latitude',
        maxlon: 'EPSG4326Longitude',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BoundingBoxCoordinates':
        return super().__new__(
            cls,
            *args,
            minlon=minlon,
            maxlat=maxlat,
            minlat=minlat,
            maxlon=maxlon,
            _configuration=_configuration,
            **kwargs,
        )

from agrimetrics_python_sdk.model.epsg4326_latitude import EPSG4326Latitude
from agrimetrics_python_sdk.model.epsg4326_longitude import EPSG4326Longitude
