# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from agrimetrics_python_sdk import schemas  # noqa: F401


class DataSets(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "dataSets",
        }
        
        class properties:
            
            
            class dataSets(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['DataSet']:
                        return DataSet
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['DataSet'], typing.List['DataSet']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'dataSets':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'DataSet':
                    return super().__getitem__(i)
        
            @staticmethod
            def concepts() -> typing.Type['Concepts']:
                return Concepts
            __annotations__ = {
                "dataSets": dataSets,
                "concepts": concepts,
            }
    
    dataSets: MetaOapg.properties.dataSets
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dataSets"]) -> MetaOapg.properties.dataSets: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["concepts"]) -> 'Concepts': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["dataSets", "concepts", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dataSets"]) -> MetaOapg.properties.dataSets: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["concepts"]) -> typing.Union['Concepts', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["dataSets", "concepts", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        dataSets: typing.Union[MetaOapg.properties.dataSets, list, tuple, ],
        concepts: typing.Union['Concepts', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DataSets':
        return super().__new__(
            cls,
            *args,
            dataSets=dataSets,
            concepts=concepts,
            _configuration=_configuration,
            **kwargs,
        )

from agrimetrics_python_sdk.model.concepts import Concepts
from agrimetrics_python_sdk.model.data_set import DataSet
