# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.spatial_coverage import SpatialCoverage
from agrimetrics_python_sdk import configuration


class TestSpatialCoverage(unittest.TestCase):
    """SpatialCoverage unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
