# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.basic_data_set_info import BasicDataSetInfo
from agrimetrics_python_sdk import configuration


class TestBasicDataSetInfo(unittest.TestCase):
    """BasicDataSetInfo unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
