# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.data_set_template_patch_metadata import DataSetTemplatePatchMetadata
from agrimetrics_python_sdk import configuration


class TestDataSetTemplatePatchMetadata(unittest.TestCase):
    """DataSetTemplatePatchMetadata unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
