# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.geo_json_multi_polygon_coordinates_item_item_item import GeoJSONMultiPolygonCoordinatesItemItemItem
from agrimetrics_python_sdk import configuration


class TestGeoJSONMultiPolygonCoordinatesItemItemItem(unittest.TestCase):
    """GeoJSONMultiPolygonCoordinatesItemItemItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
