# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.query_layer_calculate_statistics_within_geometry_request import QueryLayerCalculateStatisticsWithinGeometryRequest
from agrimetrics_python_sdk import configuration


class TestQueryLayerCalculateStatisticsWithinGeometryRequest(unittest.TestCase):
    """QueryLayerCalculateStatisticsWithinGeometryRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
