# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.data_request_response import DataRequestResponse
from agrimetrics_python_sdk import configuration


class TestDataRequestResponse(unittest.TestCase):
    """DataRequestResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
