# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.entry_update_response import EntryUpdateResponse
from agrimetrics_python_sdk import configuration


class TestEntryUpdateResponse(unittest.TestCase):
    """EntryUpdateResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
