# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.polygon_or_b_box_search import PolygonOrBBoxSearch
from agrimetrics_python_sdk import configuration


class TestPolygonOrBBoxSearch(unittest.TestCase):
    """PolygonOrBBoxSearch unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
