# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.query_layer_search_geometry_request import QueryLayerSearchGeometryRequest
from agrimetrics_python_sdk import configuration


class TestQueryLayerSearchGeometryRequest(unittest.TestCase):
    """QueryLayerSearchGeometryRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
