# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.wfs_query_data_open_gis_response import WfsQueryDataOpenGisResponse
from agrimetrics_python_sdk import configuration


class TestWfsQueryDataOpenGisResponse(unittest.TestCase):
    """WfsQueryDataOpenGisResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
