# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.authentication_get_jwt_response import AuthenticationGetJwtResponse
from agrimetrics_python_sdk import configuration


class TestAuthenticationGetJwtResponse(unittest.TestCase):
    """AuthenticationGetJwtResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
