# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.geo_json_polygon_coordinates_item import GeoJSONPolygonCoordinatesItem
from agrimetrics_python_sdk import configuration


class TestGeoJSONPolygonCoordinatesItem(unittest.TestCase):
    """GeoJSONPolygonCoordinatesItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
