# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.data_request_get_results406_response import DataRequestGetResults406Response
from agrimetrics_python_sdk import configuration


class TestDataRequestGetResults406Response(unittest.TestCase):
    """DataRequestGetResults406Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
