# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.query_layer_cut_shape_boundary_and_retrieve_response import QueryLayerCutShapeBoundaryAndRetrieveResponse
from agrimetrics_python_sdk import configuration


class TestQueryLayerCutShapeBoundaryAndRetrieveResponse(unittest.TestCase):
    """QueryLayerCutShapeBoundaryAndRetrieveResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
