# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.ogc_api_tiles_query_tile_matrix_sets_response import OgcApiTilesQueryTileMatrixSetsResponse
from agrimetrics_python_sdk import configuration


class TestOgcApiTilesQueryTileMatrixSetsResponse(unittest.TestCase):
    """OgcApiTilesQueryTileMatrixSetsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
