# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.ogc_api_tiles_get_conformance_response import OgcApiTilesGetConformanceResponse
from agrimetrics_python_sdk import configuration


class TestOgcApiTilesGetConformanceResponse(unittest.TestCase):
    """OgcApiTilesGetConformanceResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
