# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.esri_rest_service_query200_response import EsriRestServiceQuery200Response
from agrimetrics_python_sdk import configuration


class TestEsriRestServiceQuery200Response(unittest.TestCase):
    """EsriRestServiceQuery200Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
