# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.iso8601_datetime import ISO8601Datetime
from agrimetrics_python_sdk import configuration


class TestISO8601Datetime(unittest.TestCase):
    """ISO8601Datetime unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
