# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.template_list_permissions_to_view_response import TemplateListPermissionsToViewResponse
from agrimetrics_python_sdk import configuration


class TestTemplateListPermissionsToViewResponse(unittest.TestCase):
    """TemplateListPermissionsToViewResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
