# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

import unittest

import agrimetrics_python_sdk
from agrimetrics_python_sdk.model.data_request_create_single_access_request_response import DataRequestCreateSingleAccessRequestResponse
from agrimetrics_python_sdk import configuration


class TestDataRequestCreateSingleAccessRequestResponse(unittest.TestCase):
    """DataRequestCreateSingleAccessRequestResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
