# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from agrimetrics_python_sdk.type.authentication_get_jwt_response_jwts_agrimetrics import AuthenticationGetJwtResponseJwtsAgrimetrics

class RequiredAuthenticationGetJwtResponseJwts(TypedDict):
    pass

class OptionalAuthenticationGetJwtResponseJwts(TypedDict, total=False):
    agrimetrics: AuthenticationGetJwtResponseJwtsAgrimetrics

class AuthenticationGetJwtResponseJwts(RequiredAuthenticationGetJwtResponseJwts, OptionalAuthenticationGetJwtResponseJwts):
    pass
