# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDataRequestCreateSingleAccessRequestResponse(TypedDict):
    pass

class OptionalDataRequestCreateSingleAccessRequestResponse(TypedDict, total=False):
    message: str

class DataRequestCreateSingleAccessRequestResponse(RequiredDataRequestCreateSingleAccessRequestResponse, OptionalDataRequestCreateSingleAccessRequestResponse):
    pass
