# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from agrimetrics_python_sdk.type.concepts import Concepts
from agrimetrics_python_sdk.type.data_set import DataSet

class RequiredDataSets(TypedDict):
    # An array of data sets
    dataSets: typing.List[DataSet]

class OptionalDataSets(TypedDict, total=False):
    concepts: Concepts

class DataSets(RequiredDataSets, OptionalDataSets):
    pass
