# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from agrimetrics_python_sdk.type.category_value import CategoryValue
from agrimetrics_python_sdk.type.contact import Contact
from agrimetrics_python_sdk.type.data_format import DataFormat
from agrimetrics_python_sdk.type.data_set_patch_alternative_titles import DataSetPatchAlternativeTitles
from agrimetrics_python_sdk.type.data_set_patch_derived_from import DataSetPatchDerivedFrom
from agrimetrics_python_sdk.type.data_set_patch_distributions import DataSetPatchDistributions
from agrimetrics_python_sdk.type.data_set_patch_geospatial_extent import DataSetPatchGeospatialExtent
from agrimetrics_python_sdk.type.data_set_patch_licence import DataSetPatchLicence
from agrimetrics_python_sdk.type.data_set_patch_metadata_contact import DataSetPatchMetadataContact
from agrimetrics_python_sdk.type.data_set_patch_tags import DataSetPatchTags
from agrimetrics_python_sdk.type.data_set_patch_temporal_extent import DataSetPatchTemporalExtent
from agrimetrics_python_sdk.type.published_status import PublishedStatus
from agrimetrics_python_sdk.type.resource import Resource
from agrimetrics_python_sdk.type.taxonomy_keywords import TaxonomyKeywords
from agrimetrics_python_sdk.type.topic import Topic
from agrimetrics_python_sdk.type.workflow_keywords import WorkflowKeywords

class RequiredDataSetPatch(TypedDict):
    pass

class OptionalDataSetPatch(TypedDict, total=False):
    tags: typing.Optional[DataSetPatchTags]

    # Summary of the data set.
    summary: str

    # Title for the data set.
    title: str

    # Description of the data set.
    description: str

    alternativeTitles: DataSetPatchAlternativeTitles

    # ScoringURI for the model.
    scoringURI: str

    # Endpoint key for the model.
    endpointKey: str

    derivedFrom: typing.Optional[DataSetPatchDerivedFrom]

    # Creator of the data set.
    creator: typing.Optional[str]

    # Free text description about the reliability of this dataset.
    dataReliability: typing.Optional[str]

    # WARNING: This property is deprecated
    # License of the data set.
    license: typing.Optional[str]

    licence: typing.Optional[DataSetPatchLicence]

    # Links containing more information on the data set
    resources: typing.Optional[typing.List[Resource]]

    # Format of the data set
    dataFormats: typing.Optional[typing.List[DataFormat]]

    # The geo spatial coverage of the data set.
    spatialCoverage: typing.Optional[str]

    # The resolution of data set in meters.
    spatialResolution: typing.Optional[typing.Union[int, float]]

    geospatialExtent: typing.Optional[DataSetPatchGeospatialExtent]

    # The time frame this data set covers.
    temporalCoverage: typing.Optional[str]

    temporalExtent: DataSetPatchTemporalExtent

    # The sampling time period of the data set.
    temporalResolution: typing.Optional[str]

    topics: typing.List[Topic]

    # List of workflow keywords on this data set
    workflowKeywords: typing.List[WorkflowKeywords]

    # List of keywords based on specific taxonomies
    taxonomyKeywords: typing.List[TaxonomyKeywords]

    # The frequency at which data set is published.
    accrualPeriodicity: typing.Optional[str]

    # The date when the data set was issued.
    issued: typing.Optional[str]

    # Data set creation timestamp.
    createdAt: typing.Optional[typing.Union[int, float]]

    # Data set publication timestamp.
    published: typing.Optional[typing.Union[int, float]]

    publishedStatus: PublishedStatus

    # An timestamp of when the data in this dataset was last updated
    modified: typing.Optional[typing.Union[int, float]]

    category: CategoryValue

    # Whether or not this data set should be displayed in the index.
    visibility: str

    # Pricing description of the data set.
    pricingDescription: str

    distributions: DataSetPatchDistributions

    # Approval for access status number
    approvalForAccessNumber: typing.Optional[typing.Union[int, float]]

    # Approval for access status value
    approvalForAccessStatus: typing.Optional[str]

    # List of contacts for this data set
    contacts: typing.List[Contact]

    metadataContact: typing.Optional[DataSetPatchMetadataContact]

    # Information about the creation and quality assurance process of the dataset
    lineage: typing.Optional[str]

    # Language used on the data set
    language: typing.Optional[str]

    # Character set used on the data set
    characterSet: typing.Optional[str]

    # Hierarchy level of the data set
    hierarchyLevel: typing.Optional[str]

    # Language used on the metadata
    metadataLanguage: typing.Optional[str]

    # Character set used on the metadata
    metadataCharacterSet: typing.Optional[str]

    metadataStandardName: typing.Optional[str]

    metadataStandardVersion: typing.Optional[str]

    # URL to the specification of the coordinate system used in the data
    coordinateReferenceSystemId: typing.Optional[str]

    # Type of the geospatial data
    spatialRepresentationType: typing.Optional[str]

class DataSetPatch(RequiredDataSetPatch, OptionalDataSetPatch):
    pass
