# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDataSetPatchMetadataContact(TypedDict):
    # Organisation name for this contact
    organisationName: str

    # The role of this contact as it relates to the data set
    role: str

class OptionalDataSetPatchMetadataContact(TypedDict, total=False):
    # Individual name for this contact
    individualName: str

    # Email address for this contact
    emailAddress: str

class DataSetPatchMetadataContact(RequiredDataSetPatchMetadataContact, OptionalDataSetPatchMetadataContact):
    pass
