# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDataRequestDetailsItem(TypedDict):
    # The ID of the data request
    requestId: str

    # The ID of the dataset that the data request relates to
    datasetId: str

    # The name of the dataset that the data request relates to
    datasetName: str

    # The status of the data request
    status: str

    # The date the data request was made
    requestedDate: str

class OptionalDataRequestDetailsItem(TypedDict, total=False):
    # The date the data request was approved or rejected
    reviewedDate: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    # The format the user would like the data to be provided in
    requestedFormat: str

    # The name of the project the data is for
    projectName: str

    # The name of the project manager who can approve the request
    projectManagerName: str

    # The email address of the project manager who can approve the request
    projectManagerEmail: str

    # The email of the person who made the data request
    requesterEmail: str

    # The date until which the data from an approved request can be downloaded
    expiryDate: str

    uniqueLinkId: str

class DataRequestDetailsItem(RequiredDataRequestDetailsItem, OptionalDataRequestDetailsItem):
    pass
