# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from agrimetrics_python_sdk.type.bounding_box import BoundingBox
from agrimetrics_python_sdk.type.geo_json_multi_polygon import GeoJSONMultiPolygon
from agrimetrics_python_sdk.type.geo_json_polygon import GeoJSONPolygon

GeneralGeometry = typing.Union[BoundingBox,GeoJSONPolygon,GeoJSONMultiPolygon]
