# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from agrimetrics_python_sdk.type.geo_json_multi_polygon_coordinates_item_item_item import GeoJSONMultiPolygonCoordinatesItemItemItem

GeoJSONMultiPolygonCoordinatesItemItem = typing.List[GeoJSONMultiPolygonCoordinatesItemItemItem]
