# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from agrimetrics_python_sdk.type.image_representation_author import ImageRepresentationAuthor

class RequiredImageRepresentation(TypedDict):
    pass

class OptionalImageRepresentation(TypedDict, total=False):
    type: str

    url: str

    thumbnailUrl: str

    author: ImageRepresentationAuthor

class ImageRepresentation(RequiredImageRepresentation, OptionalImageRepresentation):
    pass
