# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from agrimetrics_python_sdk.type.iso8601_datetime import ISO8601Datetime

class RequiredManageLayerAddGeoTiffRequest(TypedDict):
    pass

class OptionalManageLayerAddGeoTiffRequest(TypedDict, total=False):
    datetime: ISO8601Datetime

    # The file to upload.
    file: typing.IO

class ManageLayerAddGeoTiffRequest(RequiredManageLayerAddGeoTiffRequest, OptionalManageLayerAddGeoTiffRequest):
    pass
