# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from agrimetrics_python_sdk.type.output_formats import OutputFormats
from agrimetrics_python_sdk.type.point_search_base import PointSearchBase

PointSearch = typing.Union[PointSearchBase,typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
