# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredQueryLayerCutShapeBoundaryAndRetrieve404Response(TypedDict):
    message: str

class OptionalQueryLayerCutShapeBoundaryAndRetrieve404Response(TypedDict, total=False):
    pass

class QueryLayerCutShapeBoundaryAndRetrieve404Response(RequiredQueryLayerCutShapeBoundaryAndRetrieve404Response, OptionalQueryLayerCutShapeBoundaryAndRetrieve404Response):
    pass
