# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from agrimetrics_python_sdk.type.general_geometry import GeneralGeometry

class RequiredQueryLayerCalculateStatisticsWithinGeometryRequest(TypedDict):
    geometry: GeneralGeometry

class OptionalQueryLayerCalculateStatisticsWithinGeometryRequest(TypedDict, total=False):
    time: datetime

class QueryLayerCalculateStatisticsWithinGeometryRequest(RequiredQueryLayerCalculateStatisticsWithinGeometryRequest, OptionalQueryLayerCalculateStatisticsWithinGeometryRequest):
    pass
