# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from agrimetrics_python_sdk.type.billable import Billable

class RequiredServiceDefinitionUpdateExistingDefinitionRequest(TypedDict):
    pass

class OptionalServiceDefinitionUpdateExistingDefinitionRequest(TypedDict, total=False):
    billable: Billable

    defaultEPSGCode: typing.Union[int, float]

class ServiceDefinitionUpdateExistingDefinitionRequest(RequiredServiceDefinitionUpdateExistingDefinitionRequest, OptionalServiceDefinitionUpdateExistingDefinitionRequest):
    pass
