# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from agrimetrics_python_sdk.paths.access_requests.post import CreateNewRequestRaw
from agrimetrics_python_sdk.paths.access_requests_request_id.delete import DeleteRequestByIdRaw
from agrimetrics_python_sdk.paths.access_requests.get import ListRaw


class AccessRequestApiRaw(
    CreateNewRequestRaw,
    DeleteRequestByIdRaw,
    ListRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
