# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from agrimetrics_python_sdk.paths.service_definition.post import CreateNewDefinitionRaw
from agrimetrics_python_sdk.paths.service_definition_layer_id.delete import DeleteByIdRaw
from agrimetrics_python_sdk.paths.layers_layer_id.delete import DeleteLayerRaw
from agrimetrics_python_sdk.paths.service_definition_layer_id.get import GetByLayerIdRaw
from agrimetrics_python_sdk.paths.layers_layer_id_ingest.post import IngestFileRaw
from agrimetrics_python_sdk.paths.datasets_dataset_id_layers.post import IngestFileNewLayerRaw
from agrimetrics_python_sdk.paths.layers_layer_id_files.delete import RemoveFileRaw
from agrimetrics_python_sdk.paths.service_definition_layer_id.patch import UpdateExistingDefinitionRaw


class AdminApiRaw(
    CreateNewDefinitionRaw,
    DeleteByIdRaw,
    DeleteLayerRaw,
    GetByLayerIdRaw,
    IngestFileRaw,
    IngestFileNewLayerRaw,
    RemoveFileRaw,
    UpdateExistingDefinitionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
