# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from agrimetrics_python_sdk.paths._import.post import DataSets
from agrimetrics_python_sdk.apis.tags.model_import_api_raw import ModelImportApiRaw


class ModelImportApi(
    DataSets,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ModelImportApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ModelImportApiRaw(api_client)
