# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from agrimetrics_python_sdk.paths.datasets_dataset_id_ogc_tiles_v1_conformance.get import GetConformance
from agrimetrics_python_sdk.paths.datasets_dataset_id_ogc_tiles_v1_collections_collection_id_map_tiles_tile_matrix_set_id_tile_matrix_tile_row_tile_col.get import GetQueryTilesCollection
from agrimetrics_python_sdk.paths.datasets_dataset_id_ogc_tiles_v1_collections_collection_id_tiles_tile_matrix_set_id.get import GetTilesCollection
from agrimetrics_python_sdk.paths.datasets_dataset_id_ogc_tiles_v1_collections_collection_id.get import QueryCollectionById
from agrimetrics_python_sdk.paths.datasets_dataset_id_ogc_tiles_v1_collections_collection_id_queryables.get import QueryCollectionQueryables
from agrimetrics_python_sdk.paths.datasets_dataset_id_ogc_tiles_v1_collections.get import QueryCollections
from agrimetrics_python_sdk.paths.datasets_dataset_id_ogc_tiles_v1_tile_matrix_sets.get import QueryTileMatrixSets
from agrimetrics_python_sdk.paths.datasets_dataset_id_ogc_tiles_v1_tile_matrix_sets_tile_matrix_set_id.get import QueryTileMatrixSets0
from agrimetrics_python_sdk.paths.datasets_dataset_id_ogc_tiles_v1.get import QueryTilesV1
from agrimetrics_python_sdk.apis.tags.ogcapi_tiles_api_raw import OGCAPITilesApiRaw


class OGCAPITilesApi(
    GetConformance,
    GetQueryTilesCollection,
    GetTilesCollection,
    QueryCollectionById,
    QueryCollectionQueryables,
    QueryCollections,
    QueryTileMatrixSets,
    QueryTileMatrixSets0,
    QueryTilesV1,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OGCAPITilesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OGCAPITilesApiRaw(api_client)
