# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from agrimetrics_python_sdk.paths.service_definition.post import CreateNewDefinitionRaw
from agrimetrics_python_sdk.paths.service_definition_layer_id.delete import DeleteByIdRaw
from agrimetrics_python_sdk.paths.service_definition_layer_id.get import GetByLayerIdRaw
from agrimetrics_python_sdk.paths.service_definition_layer_id.patch import UpdateExistingDefinitionRaw


class ServiceDefinitionApiRaw(
    CreateNewDefinitionRaw,
    DeleteByIdRaw,
    GetByLayerIdRaw,
    UpdateExistingDefinitionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
