# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from agrimetrics_python_sdk.paths.shapefile.post import ConvertToGeoJson
from agrimetrics_python_sdk.apis.tags.shapefile_api_raw import ShapefileApiRaw


class ShapefileApi(
    ConvertToGeoJson,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ShapefileApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ShapefileApiRaw(api_client)
