# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from agrimetrics_python_sdk.paths.status.get import GetCatalogApiStatus
from agrimetrics_python_sdk.paths.data_sets_data_set_id_draft_status.put import SetDraftStatus
from agrimetrics_python_sdk.apis.tags.status_api_raw import StatusApiRaw


class StatusApi(
    GetCatalogApiStatus,
    SetDraftStatus,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: StatusApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = StatusApiRaw(api_client)
