# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from agrimetrics_python_sdk.paths.templates.post import CreateCatalogEntry
from agrimetrics_python_sdk.paths.templates_template_id.delete import DeleteSpecificTemplate
from agrimetrics_python_sdk.paths.templates_template_id.get import GetSpecificTemplate
from agrimetrics_python_sdk.paths.templates.get import ListPermissionsToView
from agrimetrics_python_sdk.paths.templates_template_id.put import UpdateTemplateItem
from agrimetrics_python_sdk.paths.templates_template_id.patch import UpdateTemplateItem0
from agrimetrics_python_sdk.apis.tags.template_api_raw import TemplateApiRaw


class TemplateApi(
    CreateCatalogEntry,
    DeleteSpecificTemplate,
    GetSpecificTemplate,
    ListPermissionsToView,
    UpdateTemplateItem,
    UpdateTemplateItem0,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TemplateApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TemplateApiRaw(api_client)
