# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from agrimetrics_python_sdk.paths.datasets_dataset_id_wfs.head import QueryDataOpenGisRaw
from agrimetrics_python_sdk.paths.datasets_dataset_id_wfs.post import QueryDataOpenGis0Raw
from agrimetrics_python_sdk.paths.datasets_dataset_id_wfs.get import QueryDataWithOpenGisRaw


class WFSApiRaw(
    QueryDataOpenGisRaw,
    QueryDataOpenGis0Raw,
    QueryDataWithOpenGisRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
