# coding: utf-8

"""
    Catalog API

    This API lists data sets available on Agrimetrics platform.

    Generated by: https://konfigthis.com
"""

from agrimetrics_python_sdk.paths.datasets_dataset_id_wms.get import QueryLayerWithOpenGis
from agrimetrics_python_sdk.paths.datasets_dataset_id_wms.head import QueryWithOpenGis
from agrimetrics_python_sdk.apis.tags.wms_api_raw import WMSApiRaw


class WMSApi(
    QueryLayerWithOpenGis,
    QueryWithOpenGis,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WMSApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WMSApiRaw(api_client)
