# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from agrimetrics_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    AUTHENTICATE = "/authenticate"
    STATUS = "/status"
    QUERY = "/query"
    DATASETS_DATASET_ID = "/datasets/{datasetId}"
    DATASETS_DATASET_ID_LAYERS = "/datasets/{datasetId}/layers"
    SHAPEFILE = "/shapefile"
    LAYERS_LAYER_ID = "/layers/{layerId}"
    LAYERS_LAYER_ID_FILES = "/layers/{layerId}/files"
    LAYERS_LAYER_ID_INGEST = "/layers/{layerId}/ingest"
    LAYERS_LAYER_ID_STYLE = "/layers/{layerId}/style"
    LAYERS_LAYER_ID_SEARCH = "/layers/{layerId}/search"
    LAYERS_LAYER_ID_SEARCH_COST = "/layers/{layerId}/search/cost"
    LAYERS_LAYER_ID_SEARCH_STATISTICS = "/layers/{layerId}/search/statistics"
    SERVICE_DEFINITION = "/serviceDefinition"
    SERVICE_DEFINITION_LAYER_ID = "/serviceDefinition/{layerId}"
    DATAREQUESTS = "/data-requests"
    DATAREQUESTS_REQUEST_ID = "/data-requests/{requestId}"
    DATAREQUESTS_UNIQUE_LINK_ID_APPROVE = "/data-requests/{uniqueLinkId}/approve"
    DATAREQUESTS_UNIQUE_LINK_ID_REJECT = "/data-requests/{uniqueLinkId}/reject"
    DATAREQUESTS_UNIQUE_LINK_ID_GEOMETRY = "/data-requests/{uniqueLinkId}/geometry"
    DATAREQUESTS_REQUEST_ID_DOWNLOAD = "/data-requests/{requestId}/download"
    DATASETS_SWAGGERUI_SWAGGER_FILE = "/datasets/swagger-ui/{swaggerFile}"
    DATASETS_APICSS_CSS_FILE = "/datasets/apicss/{cssFile}"
    DATASETS_DATASET_ID_WMS = "/datasets/{datasetId}/wms"
    DATASETS_DATASET_ID_WMTS = "/datasets/{datasetId}/wmts"
    DATASETS_DATASET_ID_WFS = "/datasets/{datasetId}/wfs"
    DATASETS_DATASET_ID_OGC_FEATURES_V1 = "/datasets/{datasetId}/ogc/features/v1"
    DATASETS_DATASET_ID_OGC_FEATURES_V1_OPENAPI = "/datasets/{datasetId}/ogc/features/v1/openapi"
    DATASETS_DATASET_ID_OGC_FEATURES_V1_CONFORMANCE = "/datasets/{datasetId}/ogc/features/v1/conformance"
    DATASETS_DATASET_ID_OGC_FEATURES_V1_FUNCTIONS = "/datasets/{datasetId}/ogc/features/v1/functions"
    DATASETS_DATASET_ID_OGC_FEATURES_V1_COLLECTIONS = "/datasets/{datasetId}/ogc/features/v1/collections"
    DATASETS_DATASET_ID_OGC_FEATURES_V1_COLLECTIONS_COLLECTION_ID = "/datasets/{datasetId}/ogc/features/v1/collections/{collectionId}"
    DATASETS_DATASET_ID_OGC_FEATURES_V1_COLLECTIONS_COLLECTION_ID_QUERYABLES = "/datasets/{datasetId}/ogc/features/v1/collections/{collectionId}/queryables"
    DATASETS_DATASET_ID_OGC_FEATURES_V1_COLLECTIONS_COLLECTION_ID_ITEMS = "/datasets/{datasetId}/ogc/features/v1/collections/{collectionId}/items"
    DATASETS_DATASET_ID_OGC_FEATURES_V1_COLLECTIONS_COLLECTION_ID_ITEMS_FEATURE_ID = "/datasets/{datasetId}/ogc/features/v1/collections/{collectionId}/items/{featureId}"
    DATASETS_DATASET_ID_OGC_TILES_V1 = "/datasets/{datasetId}/ogc/tiles/v1"
    DATASETS_DATASET_ID_OGC_TILES_V1_CONFORMANCE = "/datasets/{datasetId}/ogc/tiles/v1/conformance"
    DATASETS_DATASET_ID_OGC_TILES_V1_COLLECTIONS = "/datasets/{datasetId}/ogc/tiles/v1/collections"
    DATASETS_DATASET_ID_OGC_TILES_V1_COLLECTIONS_COLLECTION_ID = "/datasets/{datasetId}/ogc/tiles/v1/collections/{collectionId}"
    DATASETS_DATASET_ID_OGC_TILES_V1_COLLECTIONS_COLLECTION_ID_QUERYABLES = "/datasets/{datasetId}/ogc/tiles/v1/collections/{collectionId}/queryables"
    DATASETS_DATASET_ID_OGC_TILES_V1_COLLECTIONS_COLLECTION_ID_TILES_TILE_MATRIX_SET_ID = "/datasets/{datasetId}/ogc/tiles/v1/collections/{collectionId}/tiles/{tileMatrixSetId}"
    DATASETS_DATASET_ID_OGC_TILES_V1_COLLECTIONS_COLLECTION_ID_MAP_TILES_TILE_MATRIX_SET_ID_TILE_MATRIX_TILE_ROW_TILE_COL = "/datasets/{datasetId}/ogc/tiles/v1/collections/{collectionId}/map/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}"
    DATASETS_DATASET_ID_OGC_TILES_V1_TILE_MATRIX_SETS = "/datasets/{datasetId}/ogc/tiles/v1/tileMatrixSets"
    DATASETS_DATASET_ID_OGC_TILES_V1_TILE_MATRIX_SETS_TILE_MATRIX_SET_ID = "/datasets/{datasetId}/ogc/tiles/v1/tileMatrixSets/{tileMatrixSetId}"
    DATASETS_DATASET_ID_WMTS_REST_LAYER_NAME_STYLE_TILEJSON_IMAGE_FORMAT = "/datasets/{datasetId}/wmts/rest/{layerName}/{style}/tilejson/{imageFormat}"
    DATASETS_DATASET_ID_WMTS_REST_LAYER_NAME_STYLE_TILE_MATRIX_SET_TILE_MATRIX_TILE_ROW_TILE_COL = "/datasets/{datasetId}/wmts/rest/{layerName}/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}"
    DATASETS_DATASET_ID_WMTS_REST_LAYER_NAME_STYLE_TILE_MATRIX_SET_TILE_MATRIX_TILE_ROW_TILE_COL_J_I = "/datasets/{datasetId}/wmts/rest/{layerName}/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}/{J}/{I}"
    DATASETS_DATASET_ID_WCS = "/datasets/{datasetId}/wcs"
    REST_SERVICES_DATASET_ID_PARAM_ONE = "/rest/services/{datasetId}/{paramOne}"
    REST_SERVICES_DATASET_ID_PARAM_ONE_PARAM_TWO = "/rest/services/{datasetId}/{paramOne}/{paramTwo}"
    CATEGORIES = "/categories"
    TAGS = "/tags"
    LINKEDDATA_CONCEPTS = "/linked-data/concepts"
    DATASETS = "/data-sets"
    DATASETS_DATA_SET_ID = "/data-sets/{dataSetId}"
    DATASETS_DATA_SET_ID_DRAFT = "/data-sets/{dataSetId}/draft"
    DATASETS_DATA_SET_ID_DRAFTSTATUS = "/data-sets/{dataSetId}/draft-status"
    DATASETS_DATA_SET_ID_FILE_DATASET = "/data-sets/{dataSetId}/fileDataset"
    DATASETS_DATA_SET_ID_ACCESS = "/data-sets/{dataSetId}/access"
    DATASETS_DATA_SET_ID_VALIDATION_REPORT = "/data-sets/{dataSetId}/validationReport"
    DATASETS_DATA_SET_ID_DRAFT_VALIDATION_REPORT = "/data-sets/{dataSetId}/draft/validationReport"
    IMAGES_IMAGE_TYPE_IMAGE_ID = "/images/{imageType}/{imageId}"
    DATASETS_DATA_SET_ID_IMAGE = "/data-sets/{dataSetId}/image"
    ACCESSREQUESTS = "/access-requests"
    ACCESSREQUESTS_REQUEST_ID = "/access-requests/{requestId}"
    IMPORT = "/import"
    TEMPLATES = "/templates"
    TEMPLATES_TEMPLATE_ID = "/templates/{templateId}"
    HARVEST_GROUP_CSW = "/harvest/{group}/csw"
    HARVEST_GROUP_DCAT = "/harvest/{group}/dcat"
